name: contact_manager
version: 0.0.1
author: Sergio Navarro <sergio.navarro.1@ulaval.ca>
description: A sample web application to manage contacts
homepage: http://ondart.me/
dependencies:
  browser: any
